### ISSUE TITLE
I do not think you realize what the issue is.

### ISSUE THREAD

**Issue by gvmii** [Aniell4/obsidian#1]
I think you're being absolutely dishonest.
I got you into this drug shit. 
![image](https://github.com/Aniell4/obsidian/assets/68835899/6f39d5f6-8a96-44d9-ab4e-a6f3535144f4)
![image](https://github.com/Aniell4/obsidian/assets/68835899/1244c17e-6d51-4f57-b753-e444f2443bf1)
I gave you all the information you needed to be safe, and I repeatedly warned you to be careful.
![image](https://github.com/Aniell4/obsidian/assets/68835899/1d1d22f6-d1db-42e8-989f-45a99f8b0b20)
![image](https://github.com/Aniell4/obsidian/assets/68835899/97faf9b5-e1bf-4172-9b62-a61154903e6c)
![image](https://github.com/Aniell4/obsidian/assets/68835899/62991adc-039e-4d98-b91e-3de21851a810)
You repeatedly bait and baited me, saying that my HRT was also a drug.
![image](https://github.com/Aniell4/obsidian/assets/68835899/ea817f6b-66af-49a2-82a7-d7da875782d0)
I repeated, time and time again.
![image](https://github.com/Aniell4/obsidian/assets/68835899/e08c3251-ce3f-4d53-a6c8-43105195eba8)
![image](https://github.com/Aniell4/obsidian/assets/68835899/855de122-1fca-458f-8eb2-02bdbc3f68fc)
![image](https://github.com/Aniell4/obsidian/assets/68835899/a38b2a4d-6a51-4b57-bdd6-511be3109125)
![image](https://github.com/Aniell4/obsidian/assets/68835899/ad533b37-802b-4191-973f-25e8524a1cb4)
I started becoming more aggresive, as I saw you going deeper into that hole.
![image](https://github.com/Aniell4/obsidian/assets/68835899/befed12b-253d-4f10-9136-b5dde487f0fa)
![image](https://github.com/Aniell4/obsidian/assets/68835899/8db91a56-ac14-4632-977e-ccdccada126a)
![image](https://github.com/Aniell4/obsidian/assets/68835899/9e51bb88-5a13-48b5-b994-a63d9cc77ce4)
![image](https://github.com/Aniell4/obsidian/assets/68835899/6604ec22-f57d-41b2-b3e6-52a79d0d1ed5)
I do regret things I've said, and I do regret things I've done, and this was one of them. I shouldn't had ever gotten you into this shit. I'm sorry.
![image](https://github.com/Aniell4/obsidian/assets/68835899/470f13e9-4667-4f4c-ad3d-2faa6d51e996)
![image](https://github.com/Aniell4/obsidian/assets/68835899/59e927c0-7b69-4e7a-84dd-d4ed9fc06db9)
![image](https://github.com/Aniell4/obsidian/assets/68835899/a9e2ad28-2291-49cd-8e45-271a31c4a0df)
I said that 5 months ago. "this is like watching a car crash". You won't listen, you will not see the signs, you'll still think you're right.
![image](https://github.com/Aniell4/obsidian/assets/68835899/793a1918-4e31-41e1-b1d8-3ba15c7eb74a)
HOW MANY FUCKING TIMES COULD I WARN YOU
![image](https://github.com/Aniell4/obsidian/assets/68835899/ade5bc8f-676a-4dec-9594-4b411e436f9b)
At one point. I gave up. Not on you, I never gave up on you. I just gave up on trying to be polite.
![image](https://github.com/Aniell4/obsidian/assets/68835899/0a75af89-45c0-4184-b416-3bc90cd92f59)
![image](https://github.com/Aniell4/obsidian/assets/68835899/d741da30-f734-4e89-9cec-3c5ecd782969)

I have a lot more screenshots. But this is pretty much everything I need to say. If you don't think I care, or cared, then you're blind and deaf. You promised me you were going to go sober. You didn't. I'm sorry if you feel like I'm hurting you, and I understand I am, but it's only because I care about you. I just want you to remember this in the future, I don't know what will happen, but I know you'll regret all of this. Or maybe not!
I do and did care about you, but everyone has a breaking point.
I do not have enough mental to help you with your stuff and keep myself from killing myself, i'm sorry. I have tried, I have helped you in the past. I've done things that I did not feel like doing, just to make you feel good.

You're just being ungrateful. I'm sorry you feel that way, and I know you won't look at my perspective of things, as your drug haven is a lot safer than that.

**Comment by gvmii** [comment]
You were the first that told me to "never contact you" ever again. You pushed me away. I'm sorry if you felt like you needed to, but I did not start this.

**Comment by Aniell4** [comment]
You did not start this?, i get having a breaking point, but by breaking and just being straight up toxic telling me to kill myselg because i have not helped you enough with your own problems, i do not want to spend time with you.

**Comment by gvmii** [comment]
I do not think you read my message correctly if you think I just wanted you to help me. It's the opposite, I wanted YOU to help yourself. Remember when we met? That hasn't changed. That feeling hasn't changed.

https://github.com/Aniell4/obsidian/blob/main/DO%20NOT%20TOUCH/leaving%20behind.md
also this shit is just petty.

**Comment by Aniell4** [comment]
ofc it's petty, you told me to kill myself?, you know what i left there before i made this public? my wallet seed, and a love letter to you

**Comment by gvmii** [comment]
you clearly haven't read the first post on this issue... You clearly do not know how much I care about you... I just don't think you can call me a bad person, and get the drama with my ex there for no fucking reason while repeatedly calling me toxic and not expect me to blow up. If I actually was as bad of a person as you say I am, I would've taken your seed, stole all your money and told you to fuck off. Have I ever done that? Have I ever broke your trust like that? I did not want to send you that message, but how you're acting is pretty much like you've just died. Like my best friend just died. You might not care because you're too high to care, but I left tonight's voice call crying. You do not care about how I feel. You don't care how anyone feels. If you really cared about me, you would've listened to me, you would've considered at least ONE of my warnings and this would've been completely avoided. You know way too fucking well that even if I was mid-cutting myself, if you told me "Hey Gumi, can you help me? I think I might be addicted to X and I want to help it" you know way too well I would've stopped and you'd become the number one thing in my head. Like you always were, and are. What about when I was with zalhx, luna, etc... the LSD day? The first thing I did was call you. The same the day I took lsd and went out with Luna. I fucking got back into Twitter just to see your tweets. I know you won't even read this, you won't drop your ego. That's the reason I said everything. Because it's impossible to have a conversation. You just do petty shit like this. Wow, you owned me!

**Comment by Aniell4** [comment]
you just don't understand that i do care about you, when ever have i not picked up your calls when you were self harming, or suicidal? when ever have i not tried to help you with your issues with luna, i remember once we were in a fucking call, when your mother told you bad shit about you being trans, i was fucking crying wehn you told me you were going to abandon me killing yourself. do you never fucking reazlize how much i care for you? NO YOU FUCKING DON'T, because you're always crying to yourself with you egocentrical mind, i have asked you to tripsit me before yeah, but i thought you were ok with it? why do you just not, tell me you don't want to, i would have understood and asked you if you were fucking ok!. you are just not open, never, EVER. and when you are sad you just become toxic, a really, realy tocix person that shouts at people for no real reason, so why. tell me why should i keep being friends with you?

**Comment by gvmii** [comment]
do whatever you want man, i probably won't be here in a couple of weeks so you're probably better off not having to miss me. I know you cared about me, I did care about you. That's the thing, if you ever cared about me, why did you do this? Why didn't you look for help? Why did you continue down this path, even if you knew you were both hurting you and me?

**Comment by Aniell4** [comment]
i never realized how much i was hurting you, (and you never realized how much you were hurting me). and you were never saying it, only saying it was hurting me. please don't kill yourself. i do care about you, even after everything, i will not stop my medication, but i will stop the abuse. so please seek for help. don't do anything harsh, else i will try to stop you in any way possible. you know i will.
